"""update_repo_sync_status_and_source_link

Revision ID: c9696e1b02f7
Revises: 340ed7d7acbb
Create Date: 2026-01-14 14:58:01.642470

"""

import os
from collections.abc import Sequence

from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9696e1b02f7"
down_revision: str | Sequence[str] | None = "340ed7d7acbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Default hostname for SOCPrime Expert UI (can be overridden via env variable)
DEFAULT_TDM_HOSTNAME = "tdm.socprime.com"


def upgrade() -> None:
    """Update existing repositories with sync_enabled and source_link."""
    connection = op.get_bind()

    # 1. Set sync_enabled=true for all repositories that have sync_enabled IS NULL
    # This includes local repos (which should remain null) and any existing api/external repos
    # For api and external repos, we set it to true
    connection.execute(
        text("""
            UPDATE repositories
            SET sync_enabled = true
            WHERE sync_enabled IS NULL
            AND type IN ('api', 'external')
        """)
    )

    # 2. Generate source_link for all API (SOCPrime) repositories that don't have one
    # Get the hostname from environment or use default
    tdm_hostname = os.getenv("TDM_HOSTNAME", DEFAULT_TDM_HOSTNAME)

    # Update all api repositories with generated source_link
    # Convert UUID to string for the URL
    connection.execute(
        text(f"""
            UPDATE repositories
            SET source_link = 'https://{tdm_hostname}/expert/?repositoryIds%5B%5D=' || id::text || '&repositoryType=custom'
            WHERE type = 'api'
            AND (source_link IS NULL OR source_link = '')
        """)
    )


def downgrade() -> None:
    """Revert changes - set sync_enabled to NULL and clear source_link."""
    connection = op.get_bind()

    # Revert sync_enabled for api/external repos that were updated by this migration
    # Only revert repos that have sync_enabled=true (set by this migration)
    # Note: This will revert ALL api/external repos with sync_enabled=true,
    # which is acceptable for a data migration rollback
    connection.execute(
        text("""
            UPDATE repositories
            SET sync_enabled = NULL
            WHERE type IN ('api', 'external')
            AND sync_enabled = true
        """)
    )

    # Clear source_link for api repositories that match the pattern generated by this migration
    # This will clear all api repo source_links, which is acceptable for rollback
    connection.execute(
        text("""
            UPDATE repositories
            SET source_link = NULL
            WHERE type = 'api'
            AND source_link IS NOT NULL
        """)
    )
